---
services:
  webtop:
    # image: lscr.io/linuxserver/webtop:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=WSU_ROS_DOCKER #optional
    volumes:
      #- ./config:/config
      - ./shared:/home/me485/shared
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
      - 3001:3001
      - 2222:22
      - "7400-7500:7400-7500/udp"  # DDS discovery and data
      - 5901:5901              
    # devices:
    #   - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
    networks:
      - rosnet

networks:
  rosnet:
    driver: bridge